repos:
  - repo: local
    hooks:
      - id: pylint
        name: Run pylint on src/
        entry: pylint
        language: system
        pass_filenames: true
        files: ^src/.*\.py$
        types: [python]

      - id: pytest
        name: Run pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        files: \.py$
