FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    ca-certificates \
    python3 \
    python3-venv \
    python3-dev \
    python-is-python3 \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:${PATH}"
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.70.0
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY requirements.txt /app/
COPY requirements-test.txt /app/
RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt --extra-index-url https://download.pytorch.org/whl/cpu

COPY . /app
RUN pip install --no-cache-dir -e .
RUN mkdir -p /tmp
RUN chmod 1777 /tmp
ENV PYTHONPATH=/app/src
#ENTRYPOINT ["python3", "performance_eval/main_evaluation.py"]
#CMD ["--help"]
